package com.softsimphony.checadorgdf.dao;

import com.softsimphony.checadorgdf.model.Tiporegistro;
import com.softsimphony.checadorgdf.model.TiporegistroExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TiporegistroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int countByExample(TiporegistroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int deleteByExample(TiporegistroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int deleteByPrimaryKey(Integer idTipoRegistro);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int insert(Tiporegistro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int insertSelective(Tiporegistro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    List<Tiporegistro> selectByExample(TiporegistroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    Tiporegistro selectByPrimaryKey(Integer idTipoRegistro);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Tiporegistro record, @Param("example") TiporegistroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByExample(@Param("record") Tiporegistro record, @Param("example") TiporegistroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByPrimaryKeySelective(Tiporegistro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByPrimaryKey(Tiporegistro record);
}