package com.softsimphony.checadorgdf.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class HorarioExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    public HorarioExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andIdHorarioIsNull() {
            addCriterion("idHorario is null");
            return (Criteria) this;
        }

        public Criteria andIdHorarioIsNotNull() {
            addCriterion("idHorario is not null");
            return (Criteria) this;
        }

        public Criteria andIdHorarioEqualTo(Integer value) {
            addCriterion("idHorario =", value, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioNotEqualTo(Integer value) {
            addCriterion("idHorario <>", value, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioGreaterThan(Integer value) {
            addCriterion("idHorario >", value, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioGreaterThanOrEqualTo(Integer value) {
            addCriterion("idHorario >=", value, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioLessThan(Integer value) {
            addCriterion("idHorario <", value, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioLessThanOrEqualTo(Integer value) {
            addCriterion("idHorario <=", value, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioIn(List<Integer> values) {
            addCriterion("idHorario in", values, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioNotIn(List<Integer> values) {
            addCriterion("idHorario not in", values, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioBetween(Integer value1, Integer value2) {
            addCriterion("idHorario between", value1, value2, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioNotBetween(Integer value1, Integer value2) {
            addCriterion("idHorario not between", value1, value2, "idHorario");
            return (Criteria) this;
        }

        public Criteria andHoraInicialIsNull() {
            addCriterion("horaInicial is null");
            return (Criteria) this;
        }

        public Criteria andHoraInicialIsNotNull() {
            addCriterion("horaInicial is not null");
            return (Criteria) this;
        }

        public Criteria andHoraInicialEqualTo(Date value) {
            addCriterionForJDBCTime("horaInicial =", value, "horaInicial");
            return (Criteria) this;
        }

        public Criteria andHoraInicialNotEqualTo(Date value) {
            addCriterionForJDBCTime("horaInicial <>", value, "horaInicial");
            return (Criteria) this;
        }

        public Criteria andHoraInicialGreaterThan(Date value) {
            addCriterionForJDBCTime("horaInicial >", value, "horaInicial");
            return (Criteria) this;
        }

        public Criteria andHoraInicialGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("horaInicial >=", value, "horaInicial");
            return (Criteria) this;
        }

        public Criteria andHoraInicialLessThan(Date value) {
            addCriterionForJDBCTime("horaInicial <", value, "horaInicial");
            return (Criteria) this;
        }

        public Criteria andHoraInicialLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("horaInicial <=", value, "horaInicial");
            return (Criteria) this;
        }

        public Criteria andHoraInicialIn(List<Date> values) {
            addCriterionForJDBCTime("horaInicial in", values, "horaInicial");
            return (Criteria) this;
        }

        public Criteria andHoraInicialNotIn(List<Date> values) {
            addCriterionForJDBCTime("horaInicial not in", values, "horaInicial");
            return (Criteria) this;
        }

        public Criteria andHoraInicialBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("horaInicial between", value1, value2, "horaInicial");
            return (Criteria) this;
        }

        public Criteria andHoraInicialNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("horaInicial not between", value1, value2, "horaInicial");
            return (Criteria) this;
        }

        public Criteria andHoraFinalIsNull() {
            addCriterion("horaFinal is null");
            return (Criteria) this;
        }

        public Criteria andHoraFinalIsNotNull() {
            addCriterion("horaFinal is not null");
            return (Criteria) this;
        }

        public Criteria andHoraFinalEqualTo(Date value) {
            addCriterionForJDBCTime("horaFinal =", value, "horaFinal");
            return (Criteria) this;
        }

        public Criteria andHoraFinalNotEqualTo(Date value) {
            addCriterionForJDBCTime("horaFinal <>", value, "horaFinal");
            return (Criteria) this;
        }

        public Criteria andHoraFinalGreaterThan(Date value) {
            addCriterionForJDBCTime("horaFinal >", value, "horaFinal");
            return (Criteria) this;
        }

        public Criteria andHoraFinalGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("horaFinal >=", value, "horaFinal");
            return (Criteria) this;
        }

        public Criteria andHoraFinalLessThan(Date value) {
            addCriterionForJDBCTime("horaFinal <", value, "horaFinal");
            return (Criteria) this;
        }

        public Criteria andHoraFinalLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("horaFinal <=", value, "horaFinal");
            return (Criteria) this;
        }

        public Criteria andHoraFinalIn(List<Date> values) {
            addCriterionForJDBCTime("horaFinal in", values, "horaFinal");
            return (Criteria) this;
        }

        public Criteria andHoraFinalNotIn(List<Date> values) {
            addCriterionForJDBCTime("horaFinal not in", values, "horaFinal");
            return (Criteria) this;
        }

        public Criteria andHoraFinalBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("horaFinal between", value1, value2, "horaFinal");
            return (Criteria) this;
        }

        public Criteria andHoraFinalNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("horaFinal not between", value1, value2, "horaFinal");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("descripcion is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("descripcion is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("descripcion =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("descripcion <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("descripcion >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("descripcion >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("descripcion <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("descripcion <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("descripcion like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("descripcion not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("descripcion in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("descripcion not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("descripcion between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("descripcion not between", value1, value2, "descripcion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table horario
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 18 12:11:17 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table horario
     *
     * @mbggenerated Thu Aug 18 12:11:17 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}