package com.softsimphony.checadorgdf.model;

import java.util.Date;

public class Reporte {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporte.idReporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private Integer idReporte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporte.idUsuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private Integer idUsuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporte.idArea
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private Integer idArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporte.horaRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private Date horaRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporte.fechaRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private Date fechaRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporte.idTipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private Integer idTipoRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporte.horaIdeal
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private Date horaIdeal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporte.idReporte
     *
     * @return the value of reporte.idReporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Integer getIdReporte() {
        return idReporte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporte.idReporte
     *
     * @param idReporte the value for reporte.idReporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setIdReporte(Integer idReporte) {
        this.idReporte = idReporte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporte.idUsuario
     *
     * @return the value of reporte.idUsuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporte.idUsuario
     *
     * @param idUsuario the value for reporte.idUsuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporte.idArea
     *
     * @return the value of reporte.idArea
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Integer getIdArea() {
        return idArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporte.idArea
     *
     * @param idArea the value for reporte.idArea
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setIdArea(Integer idArea) {
        this.idArea = idArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporte.horaRegistro
     *
     * @return the value of reporte.horaRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Date getHoraRegistro() {
        return horaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporte.horaRegistro
     *
     * @param horaRegistro the value for reporte.horaRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setHoraRegistro(Date horaRegistro) {
        this.horaRegistro = horaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporte.fechaRegistro
     *
     * @return the value of reporte.fechaRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporte.fechaRegistro
     *
     * @param fechaRegistro the value for reporte.fechaRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporte.idTipoRegistro
     *
     * @return the value of reporte.idTipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Integer getIdTipoRegistro() {
        return idTipoRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporte.idTipoRegistro
     *
     * @param idTipoRegistro the value for reporte.idTipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setIdTipoRegistro(Integer idTipoRegistro) {
        this.idTipoRegistro = idTipoRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporte.horaIdeal
     *
     * @return the value of reporte.horaIdeal
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Date getHoraIdeal() {
        return horaIdeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporte.horaIdeal
     *
     * @param horaIdeal the value for reporte.horaIdeal
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setHoraIdeal(Date horaIdeal) {
        this.horaIdeal = horaIdeal;
    }
}