package com.softsimphony.checadorgdf.model;

public class Tiporegistro {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipoRegistro.idTipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private Integer idTipoRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipoRegistro.nombre
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private String nombre;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipoRegistro.idTipoRegistro
     *
     * @return the value of tipoRegistro.idTipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Integer getIdTipoRegistro() {
        return idTipoRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipoRegistro.idTipoRegistro
     *
     * @param idTipoRegistro the value for tipoRegistro.idTipoRegistro
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setIdTipoRegistro(Integer idTipoRegistro) {
        this.idTipoRegistro = idTipoRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipoRegistro.nombre
     *
     * @return the value of tipoRegistro.nombre
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipoRegistro.nombre
     *
     * @param nombre the value for tipoRegistro.nombre
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}