package com.softsimphony.checadorgdf.model;

public class Usuario {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.idUsuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private Integer idUsuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.nombre
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.aPaterno
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private String aPaterno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.aMaterno
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private String aMaterno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.huellaDigital
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private String huellaDigital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.idHorario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private Integer idHorario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.idArea
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private Integer idArea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.idUsuario
     *
     * @return the value of usuario.idUsuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.idUsuario
     *
     * @param idUsuario the value for usuario.idUsuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.nombre
     *
     * @return the value of usuario.nombre
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.nombre
     *
     * @param nombre the value for usuario.nombre
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.aPaterno
     *
     * @return the value of usuario.aPaterno
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public String getaPaterno() {
        return aPaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.aPaterno
     *
     * @param aPaterno the value for usuario.aPaterno
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setaPaterno(String aPaterno) {
        this.aPaterno = aPaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.aMaterno
     *
     * @return the value of usuario.aMaterno
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public String getaMaterno() {
        return aMaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.aMaterno
     *
     * @param aMaterno the value for usuario.aMaterno
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setaMaterno(String aMaterno) {
        this.aMaterno = aMaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.huellaDigital
     *
     * @return the value of usuario.huellaDigital
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public String getHuellaDigital() {
        return huellaDigital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.huellaDigital
     *
     * @param huellaDigital the value for usuario.huellaDigital
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setHuellaDigital(String huellaDigital) {
        this.huellaDigital = huellaDigital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.idHorario
     *
     * @return the value of usuario.idHorario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Integer getIdHorario() {
        return idHorario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.idHorario
     *
     * @param idHorario the value for usuario.idHorario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.idArea
     *
     * @return the value of usuario.idArea
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Integer getIdArea() {
        return idArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.idArea
     *
     * @param idArea the value for usuario.idArea
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setIdArea(Integer idArea) {
        this.idArea = idArea;
    }
}