package com.softsimphony.checadorgdf.model;

public class Area {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.idArea
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private Integer idArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.nombre
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    private String nombre;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.idArea
     *
     * @return the value of area.idArea
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Integer getIdArea() {
        return idArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.idArea
     *
     * @param idArea the value for area.idArea
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setIdArea(Integer idArea) {
        this.idArea = idArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.nombre
     *
     * @return the value of area.nombre
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.nombre
     *
     * @param nombre the value for area.nombre
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}