package com.softsimphony.checadorgdf.model;

import java.util.ArrayList;
import java.util.List;

public class UsuarioExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public UsuarioExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdUsuarioIsNull() {
            addCriterion("idUsuario is null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIsNotNull() {
            addCriterion("idUsuario is not null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioEqualTo(Integer value) {
            addCriterion("idUsuario =", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotEqualTo(Integer value) {
            addCriterion("idUsuario <>", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGreaterThan(Integer value) {
            addCriterion("idUsuario >", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGreaterThanOrEqualTo(Integer value) {
            addCriterion("idUsuario >=", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioLessThan(Integer value) {
            addCriterion("idUsuario <", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioLessThanOrEqualTo(Integer value) {
            addCriterion("idUsuario <=", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIn(List<Integer> values) {
            addCriterion("idUsuario in", values, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotIn(List<Integer> values) {
            addCriterion("idUsuario not in", values, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioBetween(Integer value1, Integer value2) {
            addCriterion("idUsuario between", value1, value2, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotBetween(Integer value1, Integer value2) {
            addCriterion("idUsuario not between", value1, value2, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andNombreIsNull() {
            addCriterion("nombre is null");
            return (Criteria) this;
        }

        public Criteria andNombreIsNotNull() {
            addCriterion("nombre is not null");
            return (Criteria) this;
        }

        public Criteria andNombreEqualTo(String value) {
            addCriterion("nombre =", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotEqualTo(String value) {
            addCriterion("nombre <>", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThan(String value) {
            addCriterion("nombre >", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThanOrEqualTo(String value) {
            addCriterion("nombre >=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThan(String value) {
            addCriterion("nombre <", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThanOrEqualTo(String value) {
            addCriterion("nombre <=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLike(String value) {
            addCriterion("nombre like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotLike(String value) {
            addCriterion("nombre not like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreIn(List<String> values) {
            addCriterion("nombre in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotIn(List<String> values) {
            addCriterion("nombre not in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreBetween(String value1, String value2) {
            addCriterion("nombre between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotBetween(String value1, String value2) {
            addCriterion("nombre not between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andAPaternoIsNull() {
            addCriterion("aPaterno is null");
            return (Criteria) this;
        }

        public Criteria andAPaternoIsNotNull() {
            addCriterion("aPaterno is not null");
            return (Criteria) this;
        }

        public Criteria andAPaternoEqualTo(String value) {
            addCriterion("aPaterno =", value, "aPaterno");
            return (Criteria) this;
        }

        public Criteria andAPaternoNotEqualTo(String value) {
            addCriterion("aPaterno <>", value, "aPaterno");
            return (Criteria) this;
        }

        public Criteria andAPaternoGreaterThan(String value) {
            addCriterion("aPaterno >", value, "aPaterno");
            return (Criteria) this;
        }

        public Criteria andAPaternoGreaterThanOrEqualTo(String value) {
            addCriterion("aPaterno >=", value, "aPaterno");
            return (Criteria) this;
        }

        public Criteria andAPaternoLessThan(String value) {
            addCriterion("aPaterno <", value, "aPaterno");
            return (Criteria) this;
        }

        public Criteria andAPaternoLessThanOrEqualTo(String value) {
            addCriterion("aPaterno <=", value, "aPaterno");
            return (Criteria) this;
        }

        public Criteria andAPaternoLike(String value) {
            addCriterion("aPaterno like", value, "aPaterno");
            return (Criteria) this;
        }

        public Criteria andAPaternoNotLike(String value) {
            addCriterion("aPaterno not like", value, "aPaterno");
            return (Criteria) this;
        }

        public Criteria andAPaternoIn(List<String> values) {
            addCriterion("aPaterno in", values, "aPaterno");
            return (Criteria) this;
        }

        public Criteria andAPaternoNotIn(List<String> values) {
            addCriterion("aPaterno not in", values, "aPaterno");
            return (Criteria) this;
        }

        public Criteria andAPaternoBetween(String value1, String value2) {
            addCriterion("aPaterno between", value1, value2, "aPaterno");
            return (Criteria) this;
        }

        public Criteria andAPaternoNotBetween(String value1, String value2) {
            addCriterion("aPaterno not between", value1, value2, "aPaterno");
            return (Criteria) this;
        }

        public Criteria andAMaternoIsNull() {
            addCriterion("aMaterno is null");
            return (Criteria) this;
        }

        public Criteria andAMaternoIsNotNull() {
            addCriterion("aMaterno is not null");
            return (Criteria) this;
        }

        public Criteria andAMaternoEqualTo(String value) {
            addCriterion("aMaterno =", value, "aMaterno");
            return (Criteria) this;
        }

        public Criteria andAMaternoNotEqualTo(String value) {
            addCriterion("aMaterno <>", value, "aMaterno");
            return (Criteria) this;
        }

        public Criteria andAMaternoGreaterThan(String value) {
            addCriterion("aMaterno >", value, "aMaterno");
            return (Criteria) this;
        }

        public Criteria andAMaternoGreaterThanOrEqualTo(String value) {
            addCriterion("aMaterno >=", value, "aMaterno");
            return (Criteria) this;
        }

        public Criteria andAMaternoLessThan(String value) {
            addCriterion("aMaterno <", value, "aMaterno");
            return (Criteria) this;
        }

        public Criteria andAMaternoLessThanOrEqualTo(String value) {
            addCriterion("aMaterno <=", value, "aMaterno");
            return (Criteria) this;
        }

        public Criteria andAMaternoLike(String value) {
            addCriterion("aMaterno like", value, "aMaterno");
            return (Criteria) this;
        }

        public Criteria andAMaternoNotLike(String value) {
            addCriterion("aMaterno not like", value, "aMaterno");
            return (Criteria) this;
        }

        public Criteria andAMaternoIn(List<String> values) {
            addCriterion("aMaterno in", values, "aMaterno");
            return (Criteria) this;
        }

        public Criteria andAMaternoNotIn(List<String> values) {
            addCriterion("aMaterno not in", values, "aMaterno");
            return (Criteria) this;
        }

        public Criteria andAMaternoBetween(String value1, String value2) {
            addCriterion("aMaterno between", value1, value2, "aMaterno");
            return (Criteria) this;
        }

        public Criteria andAMaternoNotBetween(String value1, String value2) {
            addCriterion("aMaterno not between", value1, value2, "aMaterno");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalIsNull() {
            addCriterion("huellaDigital is null");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalIsNotNull() {
            addCriterion("huellaDigital is not null");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalEqualTo(String value) {
            addCriterion("huellaDigital =", value, "huellaDigital");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalNotEqualTo(String value) {
            addCriterion("huellaDigital <>", value, "huellaDigital");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalGreaterThan(String value) {
            addCriterion("huellaDigital >", value, "huellaDigital");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalGreaterThanOrEqualTo(String value) {
            addCriterion("huellaDigital >=", value, "huellaDigital");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalLessThan(String value) {
            addCriterion("huellaDigital <", value, "huellaDigital");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalLessThanOrEqualTo(String value) {
            addCriterion("huellaDigital <=", value, "huellaDigital");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalLike(String value) {
            addCriterion("huellaDigital like", value, "huellaDigital");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalNotLike(String value) {
            addCriterion("huellaDigital not like", value, "huellaDigital");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalIn(List<String> values) {
            addCriterion("huellaDigital in", values, "huellaDigital");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalNotIn(List<String> values) {
            addCriterion("huellaDigital not in", values, "huellaDigital");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalBetween(String value1, String value2) {
            addCriterion("huellaDigital between", value1, value2, "huellaDigital");
            return (Criteria) this;
        }

        public Criteria andHuellaDigitalNotBetween(String value1, String value2) {
            addCriterion("huellaDigital not between", value1, value2, "huellaDigital");
            return (Criteria) this;
        }

        public Criteria andIdHorarioIsNull() {
            addCriterion("idHorario is null");
            return (Criteria) this;
        }

        public Criteria andIdHorarioIsNotNull() {
            addCriterion("idHorario is not null");
            return (Criteria) this;
        }

        public Criteria andIdHorarioEqualTo(Integer value) {
            addCriterion("idHorario =", value, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioNotEqualTo(Integer value) {
            addCriterion("idHorario <>", value, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioGreaterThan(Integer value) {
            addCriterion("idHorario >", value, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioGreaterThanOrEqualTo(Integer value) {
            addCriterion("idHorario >=", value, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioLessThan(Integer value) {
            addCriterion("idHorario <", value, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioLessThanOrEqualTo(Integer value) {
            addCriterion("idHorario <=", value, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioIn(List<Integer> values) {
            addCriterion("idHorario in", values, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioNotIn(List<Integer> values) {
            addCriterion("idHorario not in", values, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioBetween(Integer value1, Integer value2) {
            addCriterion("idHorario between", value1, value2, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdHorarioNotBetween(Integer value1, Integer value2) {
            addCriterion("idHorario not between", value1, value2, "idHorario");
            return (Criteria) this;
        }

        public Criteria andIdAreaIsNull() {
            addCriterion("idArea is null");
            return (Criteria) this;
        }

        public Criteria andIdAreaIsNotNull() {
            addCriterion("idArea is not null");
            return (Criteria) this;
        }

        public Criteria andIdAreaEqualTo(Integer value) {
            addCriterion("idArea =", value, "idArea");
            return (Criteria) this;
        }

        public Criteria andIdAreaNotEqualTo(Integer value) {
            addCriterion("idArea <>", value, "idArea");
            return (Criteria) this;
        }

        public Criteria andIdAreaGreaterThan(Integer value) {
            addCriterion("idArea >", value, "idArea");
            return (Criteria) this;
        }

        public Criteria andIdAreaGreaterThanOrEqualTo(Integer value) {
            addCriterion("idArea >=", value, "idArea");
            return (Criteria) this;
        }

        public Criteria andIdAreaLessThan(Integer value) {
            addCriterion("idArea <", value, "idArea");
            return (Criteria) this;
        }

        public Criteria andIdAreaLessThanOrEqualTo(Integer value) {
            addCriterion("idArea <=", value, "idArea");
            return (Criteria) this;
        }

        public Criteria andIdAreaIn(List<Integer> values) {
            addCriterion("idArea in", values, "idArea");
            return (Criteria) this;
        }

        public Criteria andIdAreaNotIn(List<Integer> values) {
            addCriterion("idArea not in", values, "idArea");
            return (Criteria) this;
        }

        public Criteria andIdAreaBetween(Integer value1, Integer value2) {
            addCriterion("idArea between", value1, value2, "idArea");
            return (Criteria) this;
        }

        public Criteria andIdAreaNotBetween(Integer value1, Integer value2) {
            addCriterion("idArea not between", value1, value2, "idArea");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usuario
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 17 15:45:02 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}