package com.softsimphony.checadorgdf.dao;

import com.softsimphony.checadorgdf.model.Area;
import com.softsimphony.checadorgdf.model.AreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int countByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int deleteByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int deleteByPrimaryKey(Integer idArea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    List<Area> selectByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    Area selectByPrimaryKey(Integer idArea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Area record, @Param("example") AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByExample(@Param("record") Area record, @Param("example") AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByPrimaryKey(Area record);
}