package com.softsimphony.checadorgdf.dao;

import com.softsimphony.checadorgdf.model.Reporte;
import com.softsimphony.checadorgdf.model.ReporteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReporteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int countByExample(ReporteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int deleteByExample(ReporteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int deleteByPrimaryKey(Integer idReporte);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int insert(Reporte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int insertSelective(Reporte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    List<Reporte> selectByExample(ReporteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    Reporte selectByPrimaryKey(Integer idReporte);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Reporte record, @Param("example") ReporteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByExample(@Param("record") Reporte record, @Param("example") ReporteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByPrimaryKeySelective(Reporte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reporte
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByPrimaryKey(Reporte record);
}