package com.softsimphony.checadorgdf.dao;

import com.softsimphony.checadorgdf.model.Usuario;
import com.softsimphony.checadorgdf.model.UsuarioExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsuarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int countByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int deleteByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int deleteByPrimaryKey(Integer idUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int insert(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int insertSelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    List<Usuario> selectByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    Usuario selectByPrimaryKey(Integer idUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByExample(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByPrimaryKeySelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Wed Aug 17 15:45:02 CDT 2016
     */
    int updateByPrimaryKey(Usuario record);
}